"""initial_schema

Revision ID: e87ac462df0b
Revises: 
Create Date: 2026-04-14 11:36:03.926325
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e87ac462df0b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('auth_provider', sa.String(length=50), nullable=False),
    sa.Column('encrypted_token_ref', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('labels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('gmail_label_id', sa.String(length=200), nullable=True, comment='Gmail label ID after creation'),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True, comment='Hex color for UI display'),
    sa.Column('status', sa.String(length=30), nullable=False, comment='active | paused | archived'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mailbox_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('granted_scopes', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('sync_cursor', sa.String(length=100), nullable=True, comment='Gmail historyId for incremental sync'),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('watch_expiration', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False, comment='connected | syncing | error | disconnected'),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('gmail_message_id', sa.String(length=100), nullable=False),
    sa.Column('thread_id', sa.String(length=100), nullable=True),
    sa.Column('internal_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('from_header', sa.String(length=500), nullable=True),
    sa.Column('to_header', sa.Text(), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('label_ids', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('body_ref', sa.Text(), nullable=True, comment='Stored body text or reference'),
    sa.Column('raw_size', sa.Integer(), nullable=True, comment='Size estimate in bytes'),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('has_attachments', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_gmail_message_id'), 'messages', ['gmail_message_id'], unique=True)
    op.create_index(op.f('ix_messages_thread_id'), 'messages', ['thread_id'], unique=False)
    op.create_index(op.f('ix_messages_user_id'), 'messages', ['user_id'], unique=False)
    op.create_table('scopes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('include_system_labels', postgresql.ARRAY(sa.String()), nullable=True, comment='e.g. INBOX, CATEGORY_PERSONAL'),
    sa.Column('exclude_system_labels', postgresql.ARRAY(sa.String()), nullable=True, comment='e.g. CATEGORY_PROMOTIONS'),
    sa.Column('include_user_labels', postgresql.ARRAY(sa.String()), nullable=True, comment='User-created Gmail label IDs'),
    sa.Column('exclude_user_labels', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('default_date_window', sa.Integer(), nullable=False, comment='Default lookback window in days'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('threads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('gmail_thread_id', sa.String(length=100), nullable=False),
    sa.Column('subject_canonical', sa.Text(), nullable=True),
    sa.Column('participants', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('first_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threads_gmail_thread_id'), 'threads', ['gmail_thread_id'], unique=True)
    op.create_index(op.f('ix_threads_user_id'), 'threads', ['user_id'], unique=False)
    op.create_table('action_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False, comment='apply_label | remove_label | archive | mark_read'),
    sa.Column('target_refs', postgresql.ARRAY(sa.String()), nullable=True, comment='Gmail message IDs targeted'),
    sa.Column('label_id', sa.UUID(), nullable=True),
    sa.Column('preview_only', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False, comment='pending | previewing | applying | completed | failed'),
    sa.Column('result_count', sa.Integer(), nullable=True, comment='Number of messages affected'),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['label_id'], ['labels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_runs_user_id'), 'action_runs', ['user_id'], unique=False)
    op.create_table('extractions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('classifier_outputs', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Classification results as JSON'),
    sa.Column('entities_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Extracted entities'),
    sa.Column('dates_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Extracted dates/deadlines'),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    op.create_table('label_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('label_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True, comment='Plain-English meaning of the label'),
    sa.Column('inclusions', sa.Text(), nullable=True, comment='What to include — free text'),
    sa.Column('exclusions', sa.Text(), nullable=True, comment='What to exclude — free text'),
    sa.Column('confidence_threshold', sa.Float(), nullable=False),
    sa.Column('apply_mode', sa.String(length=30), nullable=False, comment='label_only | archive | mark_read'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['label_id'], ['labels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label_id')
    )
    op.create_table('query_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('raw_question', sa.Text(), nullable=False),
    sa.Column('structured_plan_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scope_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False, comment='pending | running | completed | failed'),
    sa.Column('answer_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evidence_refs', postgresql.ARRAY(sa.String()), nullable=True, comment='Message/thread IDs used as evidence'),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['scope_id'], ['scopes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_runs_user_id'), 'query_runs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_query_runs_user_id'), table_name='query_runs')
    op.drop_table('query_runs')
    op.drop_table('label_policies')
    op.drop_table('extractions')
    op.drop_index(op.f('ix_action_runs_user_id'), table_name='action_runs')
    op.drop_table('action_runs')
    op.drop_index(op.f('ix_threads_user_id'), table_name='threads')
    op.drop_index(op.f('ix_threads_gmail_thread_id'), table_name='threads')
    op.drop_table('threads')
    op.drop_table('scopes')
    op.drop_index(op.f('ix_messages_user_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_thread_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_gmail_message_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_table('mailbox_connections')
    op.drop_table('labels')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
